config/routes.rb
Rails.application.routes.draw do
  root 'twitters#index'
  resources :twitters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter.rb
class Twitter < ApplicationRecord
  validates_presence_of :message
  validates_length_of :message, minimum: 0, maximum: 280

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: [:show, :edit, :update, :destroy]

  # GET /twitters
  # GET /twitters.json
  def index
    @twitters = Twitter.all.order(created_at: :desc)
  end

  # GET /twitters/1
  # GET /twitters/1.json
  def show
  end

  # GET /twitters/new
  def new
    @twitter = Twitter.new
  end

  # GET /twitters/1/edit
  def edit
  end

  # POST /twitters
  # POST /twitters.json
  def create
    @twitter = Twitter.new(twitter_params)

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to @twitter, notice: 'Twitter was successfully created.' }
        format.json { render :show, status: :created, location: @twitter }
      else
        format.html { render :new }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitters/1
  # PATCH/PUT /twitters/1.json
  def update
    respond_to do |format|
      if @twitter.update(twitter_params)
        format.html { redirect_to @twitter, notice: 'Twitter was successfully updated.' }
        format.json { render :show, status: :ok, location: @twitter }
      else
        format.html { render :edit }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitters/1
  # DELETE /twitters/1.json
  def destroy
    @twitter.destroy
    respond_to do |format|
      format.html { redirect_to twitters_url, notice: 'Twitter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter
      @twitter = Twitter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twitter_params
      params.require(:twitter).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: twitter, local: true, class: 'text-center border border-light p-5') do |form| %>
  <p class="h4 mb-4">Tweet</p>
  <% if twitter.errors.any? %>
    <div id="error_explanation">
      <h2>Fix below <%= pluralize(twitter.errors.count, "error") %> errors:</h2>

      <ul>
        <% twitter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <label for="message">Your tweet</label>
    <%= form.text_area :message, class: 'form-control mb-4', required: true, maxlength: 280, data:{countshow: '#remaining', countable: 1}, rows: 3 %>
    <div class="small text-muted">Remaining Characters: <span id="remaining">280</span></div>
  </div>


  <%= form.submit 'Save Tweet', class:'btn btn-info' %>

<% end %>

app/views/twitters/edit.html.erb
<%= render 'form', twitter: @twitter %>

<%= link_to 'Back', twitters_path, class: 'btn btn-light' %>

app/views/twitters/index.html.erb
<%if notice %>
  <p id="notice" class="alert alert-info pt-3"><%= notice %></p>
 <% end %>

<h1>Tweets</h1>

<table class="table table-responsive-lg">
  <thead>
    <tr>
      <th class="col-md-8">Tweet</th>
      <th class="col-md-2"></th>
      <th class="col-md-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @twitters.each do |twitter| %>
      <tr>
        <td class="col-md-8">
          <p><%= twitter.message %></p>
          <p class="text-muted small"><%= twitter.created_at.to_s(:long_ordinal)%></p>
        </td>
        <td class="col-md-2">
          <%= link_to 'Edit', edit_twitter_path(twitter) %>
        </td>
        <td class="col-md-2">
          <%= link_to 'X', twitter, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twitter', new_twitter_path, class: 'btn btn-info' %>

app/views/twitters/new.html.erb
<h1>New Twitter</h1>

<%= render 'form', twitter: @twitter %>

<%= link_to 'Back', twitters_path %>

app/views/twitters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @twitter.message %>
</p>

<%= link_to 'Back', twitters_path, class: 'btn btn-light' %>